spring:




  application:
    name: catalogo
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:tests}
    username: ${DB_USER:santiago}
    password: ${DB_PASSWORD:Qwe.123*}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 16

  flyway:
    enabled: true
    baseline-on-migrate: true
    # locations: classpath:db/migration  # por defecto

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /swagger-ui.html
